- name: Install latest kernel for Ubuntu 16.04+
  apt:
    pkg: "{{ item }}"
    state: "{{ kernel_pkg_state }}"
    update_cache: yes
    cache_valid_time: 600
  with_items:
    - linux-image-extra-virtual
  when: "ansible_distribution_version|version_compare(16.04, '=')
      or install_kernel_extras"
  register: kernel_result

- name: Reboot instance
  command: /sbin/shutdown -r now
  register: reboot_result
  when: "(ansible_distribution_version|version_compare(12.04, '=') and kernel_result|changed)
      or (ansible_distribution_version|version_compare(14.04, '=') and kernel_result|changed)
      or (ansible_distribution_version|version_compare(13.10, '=') and cgroup_lite_result|changed)
      or xorg_pkg_result|changed"

- name: Wait for instance to come online (10 minute timeout)
  become: no
  local_action:
    module: wait_for
    host: "{{ ansible_ssh_host|default(inventory_hostname) }}"
    port: "{{ ansible_ssh_port|default(ssh_port) }}"
    delay: 30
    timeout: 600
    state: started
  when: "reboot_result|changed"
